import { createFileRoute } from "@tanstack/react-router";

/**
 * Deletes old PDF FILES from the `whatsapp-reports` storage bucket only.
 * Does NOT touch the `report_queue` table, `scan_submissions` table, or
 * any JSON data anywhere — those are permanent and untouched by this.
 *
 * FIXED: files here are organized into DATE-NAMED FOLDERS
 * (e.g. "2026-07-27/Test-xyz.pdf"), not stored flat in the bucket root.
 * The first version of this only listed the bucket's top level, which in
 * a folder structure like this returns the FOLDER NAMES, not the files
 * inside them — so it always found "nothing old enough," even with
 * weeks of old files actually sitting there. Confirmed directly from a
 * real listing before shipping this fix, not guessed.
 *
 * This version reads each folder's name AS the date itself (which is
 * exactly what it already is), decides directly from that whether the
 * whole folder is old enough to remove, then lists and deletes every
 * file inside it. Simpler and more reliable than trusting per-file
 * metadata, since the date is unambiguous right there in the folder name.
 *
 * Why this is safe to run automatically forever: every PDF is 100%
 * reconstructable at any time from `report_queue.report_payload` (the
 * full JSON of that scan), via the exact same pdfBytes() function that
 * built it the first time — see report-link.$scanId.ts, which rebuilds a
 * purged file on the fly the next time someone clicks its link. So this
 * never actually loses anything — it only deletes a REDUNDANT copy of
 * something that can be regenerated byte-for-byte identical.
 */
/**
 * UPDATED (per Om's request): shrunk from 15 days down to 2 — as close to
 * "don't persist the PDF at all" as is actually possible. The reason it
 * can't be zero: WhatsApp/AiSensy needs a real, fetchable URL to deliver
 * the file as an attachment — it can't be sent inline — so the file has
 * to exist for at least the short window AiSensy needs to actually fetch
 * it. 2 days is a generous safety buffer for that, while keeping storage
 * close to nothing day-to-day. Nothing is ever actually at risk of being
 * lost either way — report-link.$scanId.ts already rebuilds any missing
 * file on the spot from the permanent JSON in report_queue.report_payload.
 */
const RETENTION_DAYS = 2;
const BUCKET = "whatsapp-reports";

function parseFolderDate(folderName: string): Date | null {
  const m = folderName.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!m) return null;
  const d = new Date(Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3])));
  return isNaN(d.getTime()) ? null : d;
}

export const Route = createFileRoute("/api/public/purge-old-reports")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const configuredSecret = process.env.REPORT_QUEUE_CRON_SECRET;
        const suppliedSecret = request.headers.get("x-cron-secret");
        if (!configuredSecret || suppliedSecret !== configuredSecret) {
          return new Response("Unauthorized", { status: 401 });
        }

        const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
        const cutoff = new Date(Date.now() - RETENTION_DAYS * 24 * 60 * 60 * 1000);

        try {
          const { data: topLevel, error: listError } = await supabaseAdmin.storage
            .from(BUCKET)
            .list("", { limit: 1000 });

          if (listError) {
            return Response.json({ ok: false, error: `list: ${listError.message}` }, { status: 500 });
          }

          let deleted = 0;
          const skippedUnrecognized: string[] = [];

          for (const entry of topLevel ?? []) {
            // A real file sitting directly at the root (id is set for
            // files, null for folders) — leave anything unexpected alone.
            if (entry.id) { skippedUnrecognized.push(entry.name); continue; }

            const folderDate = parseFolderDate(entry.name);
            if (!folderDate) { skippedUnrecognized.push(entry.name); continue; }
            if (folderDate >= cutoff) continue; // this date folder is still within retention

            const { data: filesInFolder, error: subListError } = await supabaseAdmin.storage
              .from(BUCKET)
              .list(entry.name, { limit: 1000 });
            if (subListError || !filesInFolder?.length) continue;

            const fullPaths = filesInFolder.map((f) => `${entry.name}/${f.name}`);
            const { error: removeError } = await supabaseAdmin.storage.from(BUCKET).remove(fullPaths);
            if (removeError) {
              console.error("[purge-old-reports] remove failed for", entry.name, removeError);
            } else {
              deleted += fullPaths.length;
            }
          }

          return Response.json({
            ok: true, deleted, retentionDays: RETENTION_DAYS,
            skippedUnrecognized, // anything not matching YYYY-MM-DD — check these manually if this list isn't empty
          });
        } catch (error) {
          console.error("[purge-old-reports] failed", error);
          return Response.json({ ok: false, error: String((error as Error)?.message ?? error) }, { status: 500 });
        }
      },
    },
  },
});
