import { createFileRoute } from "@tanstack/react-router";

/**
 * Deletes old PDF FILES from the `whatsapp-reports` storage bucket only. * Does NOT touch the `report_queue` table, `scan_submissions` table, or
 * any JSON data anywhere — those are permanent and untouched by this.
 *
 * Why this is safe to run automatically forever: every PDF is 100%
 * reconstructable at any time from `report_queue.report_payload` (the
 * full JSON of that scan), via the exact same pdfBytes() function that
 * built it the first time — see report-link.$scanId.ts, which now
 * rebuilds a purged file on the fly the next time someone clicks its link.
 * So this never actually loses anything — it only deletes a REDUNDANT
 * copy of something that can be regenerated byte-for-byte identical.
 *
 * Uses Supabase Storage's own remove() API (not a raw SQL delete against
 * storage.objects) specifically so the underlying storage bytes are
 * guaranteed to actually be freed, not just the metadata row.
 */
const RETENTION_DAYS = 15;
const BUCKET = "whatsapp-reports";

export const Route = createFileRoute("/api/public/purge-old-reports")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const configuredSecret = process.env.REPORT_QUEUE_CRON_SECRET;
        const suppliedSecret = request.headers.get("x-cron-secret");
        if (!configuredSecret || suppliedSecret !== configuredSecret) {
          return new Response("Unauthorized", { status: 401 });
        }

        const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
        const cutoff = new Date(Date.now() - RETENTION_DAYS * 24 * 60 * 60 * 1000);

        try {
          // Storage doesn't support "delete where older than X" directly,
          // so list in pages and check each file's own created_at.
          let deleted = 0;
          let offset = 0;
          const pageSize = 100;
          // Safety cap so one run can never loop forever even on a huge bucket.
          const maxPages = 200;

          for (let page = 0; page < maxPages; page++) {
            const { data: files, error: listError } = await supabaseAdmin.storage
              .from(BUCKET)
              .list("", { limit: pageSize, offset, sortBy: { column: "created_at", order: "asc" } });

            if (listError) {
              console.error("[purge-old-reports] list failed", listError);
              break;
            }
            if (!files || files.length === 0) break;

            const oldPaths = files
              .filter((f) => f.created_at && new Date(f.created_at) < cutoff)
              .map((f) => f.name);

            if (oldPaths.length > 0) {
              const { error: removeError } = await supabaseAdmin.storage.from(BUCKET).remove(oldPaths);
              if (removeError) {
                console.error("[purge-old-reports] remove failed", removeError);
              } else {
                deleted += oldPaths.length;
              }
            }

            // Files are sorted oldest-first, so once a page has no old
            // files left, every later page is even newer — safe to stop.
            if (oldPaths.length < files.length) break;
            offset += pageSize;
          }

          return Response.json({ ok: true, deleted, retentionDays: RETENTION_DAYS });
        } catch (error) {
          console.error("[purge-old-reports] failed", error);
          return Response.json({ ok: false, error: String((error as Error)?.message ?? error) }, { status: 500 });
        }
      },
    },
  },
});
